backend:
  image: shreybatra/sample-backend
  service:
    name: backend-svc
    type: ClusterIP
    port: 8000

frontend:
  image: shreybatra/sample-frontend
  service:
    name: frontend-svc
    type: NodePort
    port: 5175
    nodePort: 31000

redis:
  image: redis
  service:
    name: redis-svc
    type: ClusterIP
    port: 6379

