apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}
        env:
        - name: BACKEND_URL
          value: http://{{ .Values.backend.service.name }}:{{ .Values.backend.service.port }}
        ports:
        - containerPort: {{ .Values.frontend.service.port }}
